package theme

import "charm.land/lipgloss/v2"

var themes = map[string]*Theme{
	"charm": {
		Name:     "charm",
		Label:    "Charm",
		Base:     lipgloss.Color("#1a1b26"),
		Mantle:   lipgloss.Color("#16161e"),
		Crust:    lipgloss.Color("#101014"),
		Text:     lipgloss.Color("#c0caf5"),
		Subtext0: lipgloss.Color("#a9b1d6"),
		Subtext1: lipgloss.Color("#9aa5ce"),
		Surface0: lipgloss.Color("#292e42"),
		Surface1: lipgloss.Color("#3b4261"),
		Surface2: lipgloss.Color("#545c7e"),
		Overlay0: lipgloss.Color("#565f89"),
		Overlay1: lipgloss.Color("#6b7089"),
		Blue:     lipgloss.Color("#7aa2f7"),
		Lavender: lipgloss.Color("#b4befe"),
		Sapphire: lipgloss.Color("#7dcfff"),
		Sky:      lipgloss.Color("#89ddff"),
		Red:      lipgloss.Color("#f7768e"),
		Maroon:   lipgloss.Color("#ff9e64"),
		Peach:    lipgloss.Color("#ff9e64"),
		Yellow:   lipgloss.Color("#e0af68"),
		Green:    lipgloss.Color("#9ece6a"),
		Teal:     lipgloss.Color("#73daca"),
		Purple:   lipgloss.Color("#5A56E0"),
		Pink:     lipgloss.Color("#EE6FF8"),
		Indigo:   lipgloss.Color("#7571F9"),
		Fuchsia:  lipgloss.Color("#FF6AD5"),
	},
	"mocha": {
		Name:     "mocha",
		Label:    "Catppuccin Mocha",
		Base:     lipgloss.Color("#1e1e2e"),
		Mantle:   lipgloss.Color("#181825"),
		Crust:    lipgloss.Color("#11111b"),
		Text:     lipgloss.Color("#cdd6f4"),
		Subtext0: lipgloss.Color("#a6adc8"),
		Subtext1: lipgloss.Color("#bac2de"),
		Surface0: lipgloss.Color("#313244"),
		Surface1: lipgloss.Color("#45475a"),
		Surface2: lipgloss.Color("#585b70"),
		Overlay0: lipgloss.Color("#6c7086"),
		Overlay1: lipgloss.Color("#7f849c"),
		Blue:     lipgloss.Color("#89b4fa"),
		Lavender: lipgloss.Color("#b4befe"),
		Sapphire: lipgloss.Color("#74c7ec"),
		Sky:      lipgloss.Color("#89dceb"),
		Red:      lipgloss.Color("#f38ba8"),
		Maroon:   lipgloss.Color("#eba0ac"),
		Peach:    lipgloss.Color("#fab387"),
		Yellow:   lipgloss.Color("#f9e2af"),
		Green:    lipgloss.Color("#a6e3a1"),
		Teal:     lipgloss.Color("#94e2d5"),
		Purple:   lipgloss.Color("#5A56E0"),
		Pink:     lipgloss.Color("#EE6FF8"),
		Indigo:   lipgloss.Color("#7571F9"),
		Fuchsia:  lipgloss.Color("#cba6f7"),
	},
	"latte": {
		Name:     "latte",
		Label:    "Catppuccin Latte",
		Base:     lipgloss.Color("#eff1f5"),
		Mantle:   lipgloss.Color("#e6e9ef"),
		Crust:    lipgloss.Color("#dce0e8"),
		Text:     lipgloss.Color("#4c4f69"),
		Subtext0: lipgloss.Color("#6c6f85"),
		Subtext1: lipgloss.Color("#5c5f77"),
		Surface0: lipgloss.Color("#ccd0da"),
		Surface1: lipgloss.Color("#bcc0cc"),
		Surface2: lipgloss.Color("#acb0be"),
		Overlay0: lipgloss.Color("#9ca0b0"),
		Overlay1: lipgloss.Color("#8c8fa1"),
		Blue:     lipgloss.Color("#1e66f5"),
		Lavender: lipgloss.Color("#7287fd"),
		Sapphire: lipgloss.Color("#209fb5"),
		Sky:      lipgloss.Color("#04a5e5"),
		Red:      lipgloss.Color("#d20f39"),
		Maroon:   lipgloss.Color("#e64553"),
		Peach:    lipgloss.Color("#fe640b"),
		Yellow:   lipgloss.Color("#df8e1d"),
		Green:    lipgloss.Color("#40a02b"),
		Teal:     lipgloss.Color("#179299"),
		Purple:   lipgloss.Color("#7c3aed"),
		Pink:     lipgloss.Color("#d946ef"),
		Indigo:   lipgloss.Color("#6366f1"),
		Fuchsia:  lipgloss.Color("#8839ef"),
	},
	"dracula": {
		Name:     "dracula",
		Label:    "Dracula",
		Base:     lipgloss.Color("#282a36"),
		Mantle:   lipgloss.Color("#1e1f29"),
		Crust:    lipgloss.Color("#191a21"),
		Text:     lipgloss.Color("#f8f8f2"),
		Subtext0: lipgloss.Color("#bfbfbf"),
		Subtext1: lipgloss.Color("#e6e6e6"),
		Surface0: lipgloss.Color("#44475a"),
		Surface1: lipgloss.Color("#6272a4"),
		Surface2: lipgloss.Color("#7970a9"),
		Overlay0: lipgloss.Color("#6272a4"),
		Overlay1: lipgloss.Color("#7970a9"),
		Blue:     lipgloss.Color("#8be9fd"),
		Lavender: lipgloss.Color("#bd93f9"),
		Sapphire: lipgloss.Color("#62d6e8"),
		Sky:      lipgloss.Color("#89ddff"),
		Red:      lipgloss.Color("#ff5555"),
		Maroon:   lipgloss.Color("#ff6e6e"),
		Peach:    lipgloss.Color("#ffb86c"),
		Yellow:   lipgloss.Color("#f1fa8c"),
		Green:    lipgloss.Color("#50fa7b"),
		Teal:     lipgloss.Color("#8be9fd"),
		Purple:   lipgloss.Color("#bd93f9"),
		Pink:     lipgloss.Color("#ff79c6"),
		Indigo:   lipgloss.Color("#6272a4"),
		Fuchsia:  lipgloss.Color("#ff79c6"),
	},
	"tokyoNight": {
		Name:     "tokyoNight",
		Label:    "Tokyo Night",
		Base:     lipgloss.Color("#1a1b26"),
		Mantle:   lipgloss.Color("#16161e"),
		Crust:    lipgloss.Color("#13131a"),
		Text:     lipgloss.Color("#a9b1d6"),
		Subtext0: lipgloss.Color("#9aa5ce"),
		Subtext1: lipgloss.Color("#9aa5ce"),
		Surface0: lipgloss.Color("#232433"),
		Surface1: lipgloss.Color("#2a2b3d"),
		Surface2: lipgloss.Color("#32344a"),
		Overlay0: lipgloss.Color("#565f89"),
		Overlay1: lipgloss.Color("#6b7089"),
		Blue:     lipgloss.Color("#7aa2f7"),
		Lavender: lipgloss.Color("#bb9af7"),
		Sapphire: lipgloss.Color("#7dcfff"),
		Sky:      lipgloss.Color("#7dcfff"),
		Red:      lipgloss.Color("#f7768e"),
		Maroon:   lipgloss.Color("#ff9e64"),
		Peach:    lipgloss.Color("#ff9e64"),
		Yellow:   lipgloss.Color("#e0af68"),
		Green:    lipgloss.Color("#9ece6a"),
		Teal:     lipgloss.Color("#2ac3de"),
		Purple:   lipgloss.Color("#bb9af7"),
		Pink:     lipgloss.Color("#ff007c"),
		Indigo:   lipgloss.Color("#7aa2f7"),
		Fuchsia:  lipgloss.Color("#bb9af7"),
	},
	"gruvbox": {
		Name:     "gruvbox",
		Label:    "Gruvbox Dark",
		Base:     lipgloss.Color("#282828"),
		Mantle:   lipgloss.Color("#1d2021"),
		Crust:    lipgloss.Color("#1b1b1b"),
		Text:     lipgloss.Color("#ebdbb2"),
		Subtext0: lipgloss.Color("#a89984"),
		Subtext1: lipgloss.Color("#bdae93"),
		Surface0: lipgloss.Color("#3c3836"),
		Surface1: lipgloss.Color("#504945"),
		Surface2: lipgloss.Color("#665c54"),
		Overlay0: lipgloss.Color("#7c6f64"),
		Overlay1: lipgloss.Color("#928374"),
		Blue:     lipgloss.Color("#83a598"),
		Lavender: lipgloss.Color("#d3869b"),
		Sapphire: lipgloss.Color("#83a598"),
		Sky:      lipgloss.Color("#8ec07c"),
		Red:      lipgloss.Color("#fb4934"),
		Maroon:   lipgloss.Color("#cc241d"),
		Peach:    lipgloss.Color("#fe8019"),
		Yellow:   lipgloss.Color("#fabd2f"),
		Green:    lipgloss.Color("#b8bb26"),
		Teal:     lipgloss.Color("#8ec07c"),
		Purple:   lipgloss.Color("#d3869b"),
		Pink:     lipgloss.Color("#d3869b"),
		Indigo:   lipgloss.Color("#83a598"),
		Fuchsia:  lipgloss.Color("#d3869b"),
	},
	"nord": {
		Name:     "nord",
		Label:    "Nord",
		Base:     lipgloss.Color("#2e3440"),
		Mantle:   lipgloss.Color("#272c36"),
		Crust:    lipgloss.Color("#242933"),
		Text:     lipgloss.Color("#eceff4"),
		Subtext0: lipgloss.Color("#d8dee9"),
		Subtext1: lipgloss.Color("#e5e9f0"),
		Surface0: lipgloss.Color("#3b4252"),
		Surface1: lipgloss.Color("#434c5e"),
		Surface2: lipgloss.Color("#4c566a"),
		Overlay0: lipgloss.Color("#616e88"),
		Overlay1: lipgloss.Color("#7b88a1"),
		Blue:     lipgloss.Color("#88c0d0"),
		Lavender: lipgloss.Color("#b48ead"),
		Sapphire: lipgloss.Color("#81a1c1"),
		Sky:      lipgloss.Color("#88c0d0"),
		Red:      lipgloss.Color("#bf616a"),
		Maroon:   lipgloss.Color("#d08770"),
		Peach:    lipgloss.Color("#d08770"),
		Yellow:   lipgloss.Color("#ebcb8b"),
		Green:    lipgloss.Color("#a3be8c"),
		Teal:     lipgloss.Color("#8fbcbb"),
		Purple:   lipgloss.Color("#b48ead"),
		Pink:     lipgloss.Color("#b48ead"),
		Indigo:   lipgloss.Color("#81a1c1"),
		Fuchsia:  lipgloss.Color("#b48ead"),
	},
	"oneDark": {
		Name:     "oneDark",
		Label:    "One Dark",
		Base:     lipgloss.Color("#282c34"),
		Mantle:   lipgloss.Color("#21252b"),
		Crust:    lipgloss.Color("#1b1f23"),
		Text:     lipgloss.Color("#abb2bf"),
		Subtext0: lipgloss.Color("#828997"),
		Subtext1: lipgloss.Color("#9da5b4"),
		Surface0: lipgloss.Color("#31353f"),
		Surface1: lipgloss.Color("#393f4a"),
		Surface2: lipgloss.Color("#4b5263"),
		Overlay0: lipgloss.Color("#636d83"),
		Overlay1: lipgloss.Color("#767d8d"),
		Blue:     lipgloss.Color("#61afef"),
		Lavender: lipgloss.Color("#c678dd"),
		Sapphire: lipgloss.Color("#56b6c2"),
		Sky:      lipgloss.Color("#56b6c2"),
		Red:      lipgloss.Color("#e06c75"),
		Maroon:   lipgloss.Color("#be5046"),
		Peach:    lipgloss.Color("#d19a66"),
		Yellow:   lipgloss.Color("#e5c07b"),
		Green:    lipgloss.Color("#98c379"),
		Teal:     lipgloss.Color("#56b6c2"),
		Purple:   lipgloss.Color("#c678dd"),
		Pink:     lipgloss.Color("#c678dd"),
		Indigo:   lipgloss.Color("#61afef"),
		Fuchsia:  lipgloss.Color("#c678dd"),
	},
	"rosePine": {
		Name:     "rosePine",
		Label:    "Rosé Pine",
		Base:     lipgloss.Color("#191724"),
		Mantle:   lipgloss.Color("#1f1d2e"),
		Crust:    lipgloss.Color("#26233a"),
		Text:     lipgloss.Color("#e0def4"),
		Subtext0: lipgloss.Color("#908caa"),
		Subtext1: lipgloss.Color("#6e6a86"),
		Surface0: lipgloss.Color("#2a2837"),
		Surface1: lipgloss.Color("#343145"),
		Surface2: lipgloss.Color("#3e3b54"),
		Overlay0: lipgloss.Color("#524f67"),
		Overlay1: lipgloss.Color("#6e6a86"),
		Blue:     lipgloss.Color("#9ccfd8"),
		Lavender: lipgloss.Color("#c4a7e7"),
		Sapphire: lipgloss.Color("#31748f"),
		Sky:      lipgloss.Color("#9ccfd8"),
		Red:      lipgloss.Color("#eb6f92"),
		Maroon:   lipgloss.Color("#ebbcba"),
		Peach:    lipgloss.Color("#f6c177"),
		Yellow:   lipgloss.Color("#f6c177"),
		Green:    lipgloss.Color("#31748f"),
		Teal:     lipgloss.Color("#9ccfd8"),
		Purple:   lipgloss.Color("#c4a7e7"),
		Pink:     lipgloss.Color("#ebbcba"),
		Indigo:   lipgloss.Color("#31748f"),
		Fuchsia:  lipgloss.Color("#c4a7e7"),
	},
	"synthwave": {
		Name:     "synthwave",
		Label:    "Synthwave",
		Base:     lipgloss.Color("#2b213a"),
		Mantle:   lipgloss.Color("#2f2444"),
		Crust:    lipgloss.Color("#33274f"),
		Text:     lipgloss.Color("#ff7edb"),
		Subtext0: lipgloss.Color("#e58ee0"),
		Subtext1: lipgloss.Color("#cb9ee6"),
		Surface0: lipgloss.Color("#392662"),
		Surface1: lipgloss.Color("#443773"),
		Surface2: lipgloss.Color("#504785"),
		Overlay0: lipgloss.Color("#625997"),
		Overlay1: lipgloss.Color("#7267aa"),
		Blue:     lipgloss.Color("#36f9f6"),
		Lavender: lipgloss.Color("#ff7edb"),
		Sapphire: lipgloss.Color("#72f1b8"),
		Sky:      lipgloss.Color("#36f9f6"),
		Red:      lipgloss.Color("#fe4450"),
		Maroon:   lipgloss.Color("#ff558f"),
		Peach:    lipgloss.Color("#ff8b39"),
		Yellow:   lipgloss.Color("#fede5d"),
		Green:    lipgloss.Color("#72f1b8"),
		Teal:     lipgloss.Color("#36f9f6"),
		Purple:   lipgloss.Color("#ff7edb"),
		Pink:     lipgloss.Color("#ff558f"),
		Indigo:   lipgloss.Color("#504785"),
		Fuchsia:  lipgloss.Color("#ff7edb"),
	},
	"solarizedDark": {
		Name:     "solarizedDark",
		Label:    "Solarized Dark",
		Base:     lipgloss.Color("#002b36"),
		Mantle:   lipgloss.Color("#073642"),
		Crust:    lipgloss.Color("#0A4C5C"),
		Text:     lipgloss.Color("#839496"),
		Subtext0: lipgloss.Color("#657b83"),
		Subtext1: lipgloss.Color("#586e75"),
		Surface0: lipgloss.Color("#00313D"),
		Surface1: lipgloss.Color("#073642"),
		Surface2: lipgloss.Color("#083C49"),
		Overlay0: lipgloss.Color("#586e75"),
		Overlay1: lipgloss.Color("#657b83"),
		Blue:     lipgloss.Color("#268bd2"),
		Lavender: lipgloss.Color("#6c71c4"),
		Sapphire: lipgloss.Color("#2aa198"),
		Sky:      lipgloss.Color("#2aa198"),
		Red:      lipgloss.Color("#dc322f"),
		Maroon:   lipgloss.Color("#cb4b16"),
		Peach:    lipgloss.Color("#cb4b16"),
		Yellow:   lipgloss.Color("#b58900"),
		Green:    lipgloss.Color("#859900"),
		Teal:     lipgloss.Color("#2aa198"),
		Purple:   lipgloss.Color("#6c71c4"),
		Pink:     lipgloss.Color("#d33682"),
		Indigo:   lipgloss.Color("#268bd2"),
		Fuchsia:  lipgloss.Color("#6c71c4"),
	},
	"highContrast": {
		Name:     "highContrast",
		Label:    "High Contrast",
		Base:     lipgloss.Color("#000000"),
		Mantle:   lipgloss.Color("#0a0a0a"),
		Crust:    lipgloss.Color("#141414"),
		Text:     lipgloss.Color("#ffffff"),
		Subtext0: lipgloss.Color("#e0e0e0"),
		Subtext1: lipgloss.Color("#f0f0f0"),
		Surface0: lipgloss.Color("#1a1a1a"),
		Surface1: lipgloss.Color("#2a2a2a"),
		Surface2: lipgloss.Color("#3a3a3a"),
		Overlay0: lipgloss.Color("#4a4a4a"),
		Overlay1: lipgloss.Color("#5a5a5a"),
		Blue:     lipgloss.Color("#00ffff"),
		Lavender: lipgloss.Color("#ff00ff"),
		Sapphire: lipgloss.Color("#00ccff"),
		Sky:      lipgloss.Color("#00ffee"),
		Red:      lipgloss.Color("#ff0000"),
		Maroon:   lipgloss.Color("#ff3333"),
		Peach:    lipgloss.Color("#ffaa00"),
		Yellow:   lipgloss.Color("#ffff00"),
		Green:    lipgloss.Color("#00ff00"),
		Teal:     lipgloss.Color("#00ffcc"),
		Purple:   lipgloss.Color("#ff00ff"),
		Pink:     lipgloss.Color("#ff69b4"),
		Indigo:   lipgloss.Color("#00ccff"),
		Fuchsia:  lipgloss.Color("#ff00ff"),
	},
	"terminal": {
		Name:     "terminal",
		Label:    "Green Terminal",
		Base:     lipgloss.Color("#0D1117"),
		Mantle:   lipgloss.Color("#161B22"),
		Crust:    lipgloss.Color("#1B2127"),
		Text:     lipgloss.Color("#00FF00"),
		Subtext0: lipgloss.Color("#00D700"),
		Subtext1: lipgloss.Color("#00BB00"),
		Surface0: lipgloss.Color("#1C2128"),
		Surface1: lipgloss.Color("#21262D"),
		Surface2: lipgloss.Color("#282E35"),
		Overlay0: lipgloss.Color("#008800"),
		Overlay1: lipgloss.Color("#006600"),
		Blue:     lipgloss.Color("#00FF00"),
		Lavender: lipgloss.Color("#00FF66"),
		Sapphire: lipgloss.Color("#00DD88"),
		Sky:      lipgloss.Color("#00FFBB"),
		Red:      lipgloss.Color("#FF0000"),
		Maroon:   lipgloss.Color("#AA0000"),
		Peach:    lipgloss.Color("#00FF99"),
		Yellow:   lipgloss.Color("#FFFF00"),
		Green:    lipgloss.Color("#00FF00"),
		Teal:     lipgloss.Color("#00FFCC"),
		Purple:   lipgloss.Color("#00FF66"),
		Pink:     lipgloss.Color("#00FF99"),
		Indigo:   lipgloss.Color("#00DD88"),
		Fuchsia:  lipgloss.Color("#00FF66"),
	},
	"amber": {
		Name:     "amber",
		Label:    "Amber Terminal",
		Base:     lipgloss.Color("#0D0904"),
		Mantle:   lipgloss.Color("#160E06"),
		Crust:    lipgloss.Color("#1B1109"),
		Text:     lipgloss.Color("#FFB000"),
		Subtext0: lipgloss.Color("#CC8800"),
		Subtext1: lipgloss.Color("#995500"),
		Surface0: lipgloss.Color("#1C1409"),
		Surface1: lipgloss.Color("#211909"),
		Surface2: lipgloss.Color("#281E0A"),
		Overlay0: lipgloss.Color("#663300"),
		Overlay1: lipgloss.Color("#442200"),
		Blue:     lipgloss.Color("#FFB000"),
		Lavender: lipgloss.Color("#FFAA00"),
		Sapphire: lipgloss.Color("#FF9500"),
		Sky:      lipgloss.Color("#FFB000"),
		Red:      lipgloss.Color("#FF3300"),
		Maroon:   lipgloss.Color("#CC3300"),
		Peach:    lipgloss.Color("#FFAA55"),
		Yellow:   lipgloss.Color("#FFDD00"),
		Green:    lipgloss.Color("#FFB000"),
		Teal:     lipgloss.Color("#FFC000"),
		Purple:   lipgloss.Color("#FFAA00"),
		Pink:     lipgloss.Color("#FFAA55"),
		Indigo:   lipgloss.Color("#FF9500"),
		Fuchsia:  lipgloss.Color("#FFAA00"),
	},
	"monokaiPro": {
		Name:     "monokaiPro",
		Label:    "Monokai Pro",
		Base:     lipgloss.Color("#2d2a2e"),
		Mantle:   lipgloss.Color("#221f22"),
		Crust:    lipgloss.Color("#1b1b1b"),
		Text:     lipgloss.Color("#fcfcfa"),
		Subtext0: lipgloss.Color("#939293"),
		Subtext1: lipgloss.Color("#c1c0c0"),
		Surface0: lipgloss.Color("#403e41"),
		Surface1: lipgloss.Color("#565457"),
		Surface2: lipgloss.Color("#69676c"),
		Overlay0: lipgloss.Color("#727072"),
		Overlay1: lipgloss.Color("#848486"),
		Blue:     lipgloss.Color("#78dce8"),
		Lavender: lipgloss.Color("#ab9df2"),
		Sapphire: lipgloss.Color("#66d9ef"),
		Sky:      lipgloss.Color("#78dce8"),
		Red:      lipgloss.Color("#ff6188"),
		Maroon:   lipgloss.Color("#ff6188"),
		Peach:    lipgloss.Color("#fc9867"),
		Yellow:   lipgloss.Color("#ffd866"),
		Green:    lipgloss.Color("#a9dc76"),
		Teal:     lipgloss.Color("#78dce8"),
		Purple:   lipgloss.Color("#ab9df2"),
		Pink:     lipgloss.Color("#ff6188"),
		Indigo:   lipgloss.Color("#78dce8"),
		Fuchsia:  lipgloss.Color("#ab9df2"),
	},
}

// GetTheme returns a theme by name (defaults to charm)
func GetTheme(name string) *Theme {
	if t, ok := themes[name]; ok {
		return t
	}
	return themes["charm"]
}

// ThemeNames returns all available theme names in display order
func ThemeNames() []string {
	return []string{
		"charm",
		"mocha",
		"latte",
		"dracula",
		"tokyoNight",
		"gruvbox",
		"nord",
		"oneDark",
		"rosePine",
		"synthwave",
		"solarizedDark",
		"monokaiPro",
		"highContrast",
		"terminal",
		"amber",
	}
}
